apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
        - name: webapp
          image: niiadu/web-application
          ports:
            - containerPort: 8080
         
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    name: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
